name: 清理 Cloudflare Pages 部署

on:
  workflow_dispatch:
    inputs:
      CF_PAGES_PROJECT_NAME:
        description: 'Cloudflare Pages 项目名称'
        required: true
        type: string

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Parse input parameters
        id: parse_inputs
        run: |
          echo "CF_PAGES_PROJECT_NAME=${{ github.event.inputs.CF_PAGES_PROJECT_NAME }}" >> $GITHUB_ENV
          echo "CF_API_TOKEN=${{ secrets.CF_API_TOKEN }}" >> $GITHUB_ENV
          echo "CF_ACCOUNT_ID=${{ secrets.CF_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "CF_DELETE_ALIASED_DEPLOYMENTS=${{ secrets.CF_DELETE_ALIASED_DEPLOYMENTS }}" >> $GITHUB_ENV
        shell: bash

      - name: Run Cleanup Script
        run: node index.js
